## Libs and Model Init

In [21]:
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

pretrained= "mdhugol/indonesia-bert-sentiment-classification"

model = AutoModelForSequenceClassification.from_pretrained(pretrained)
tokenizer = AutoTokenizer.from_pretrained(pretrained)

sentiment_analysis = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

Device set to use cpu

## Sample Test

In [17]:
sample_txt = input("Masukkan kalimat contoh untuk di Tes : ")
label_index = {'LABEL_0': 'positive', 'LABEL_1': 'neutral', 'LABEL_2': 'negative'}
result = sentiment_analysis(sample_txt)
status = label_index[result[0]['label']]
score = result[0]['score']
print(f'Text: {pos_text} | Label : {status} ({score * 100:.3f}%)')

print('kalimat yang dites : ', sample_txt)
print('Label              : ', status)
print(f'Score              : {score * 100:.3f}%')

Text: Sangat bahagia hari ini | Label : negative (99.117%)
kalimat yang dites :  Dia cantik kali ya, sangking cantiknya aku jadi benci
Label              :  negative
Score              : 99.117%

## Datasets Test

### Import Datasets

In [19]:
import os
from getpass import getpass

os.environ["GITHUB_USERNAME"] = input("GitHub username: ")
os.environ["GITHUB_TOKEN"] = getpass("GitHub token: ")

!git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/qee20/productsentiment.git

fatal: destination path 'productsentiment' already exists and is not an empty directory.

In [20]:
import pandas as pd
ytcomment_df = pd.read_csv("/content/productsentiment/datasets/cleanedytcomment.csv")
ytcomment_df.head()

                                       clean_comment
0                 mau nanya ini ada ia camera nya ga
1               solusi buat ngatasin iklan di hp ini
2  hp kampret ini mah nyesel beli setiap updateny...
3                 bang ada stabilizer nya buat rekam
4  tentu ada kalo mau lebih stabil pake gimbal st...

In [22]:
texts = ytcomment_df["clean_comment"].astype(str).tolist()
print("Jumlah data:", len(texts))

Jumlah data: 6128

## Inference Batching

In [23]:
from tqdm import tqdm

batch_size = 64  # GPU T4 aman (bisa 128 kalau VRAM cukup)

results = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch_texts = texts[i:i + batch_size]

    outputs = sentiment_analysis(batch_texts)

    for out in outputs:
        results.append({
            "label": label_index[out["label"]],
            "score": out["score"]
        })

100%|██████████| 96/96 [11:45<00:00,  7.35s/it]

## Put it on mytab

In [24]:
results_df = pd.DataFrame(results)

ytcomment_df["sentiment"] = results_df["label"]
ytcomment_df["confidence"] = results_df["score"]

ytcomment_df.head()

                                       clean_comment sentiment  confidence
0                 mau nanya ini ada ia camera nya ga   neutral    0.996536
1               solusi buat ngatasin iklan di hp ini   neutral    0.976811
2  hp kampret ini mah nyesel beli setiap updateny...  negative    0.998070
3                 bang ada stabilizer nya buat rekam   neutral    0.998069
4  tentu ada kalo mau lebih stabil pake gimbal st...   neutral    0.572320

## Saving result

In [30]:
!mkdir result

### Saving on Colab

In [33]:
ytcomment_df.to_csv("/content/result/labelledytcomment.csv", index=False)
print("Saved to /content/result/labelledytcomment.csv   on colab")

Saved to /content/result/labelledytcomment.csv   on colab

### Saving on relative path

In [ ]:
ytcomment_df.to_csv("../datasets/labelledytcomment.csv", index=False)
print("Saved to datasets/labelledytcomment.csv   on relative path")