## Libs and Model Init

In [ ]:
#!pip install torch
#!pip install torch --index-url https://download.pytorch.org/whl/cpu
!pip install transformers

Collecting transformers
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: filelock in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from transformers) (3.20.1)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Collecting numpy>=1.17 (from transformers)
  Downloading numpy-2.3.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from transformers) (25.0)
Collecting pyyaml>=5.1 (from transformers)
  Downloading pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2025.11.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from transformers) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: fsspec>=2023.5.0 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.34.0->transformers)
  Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from requests->transformers) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/user/productsentiment/.venv/lib/python3.11/site-packages (from requests->transformers) (2025.11.12)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 74.3 MB/s eta 0:00:00:00:01:01
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.1/566.1 kB 34.5 MB/s eta 0:00:00
Downloading numpy-2.3.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 68.8 MB/s eta 0:00:00:00:0100:01
Downloading pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (806 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 806.6/806.6 kB 45.3 MB/s eta 0:00:00
Downloading regex-2025.11.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (800 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 800.4/800.4 kB 48.4 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 34.8 MB/s eta 0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 72.8 MB/s eta 0:00:00:00:01
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 7.8 MB/s eta 0:00:00
Downloading hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 73.9 MB/s eta 0:00:00:00:01
Installing collected packages: tqdm, safetensors, regex, pyyaml, numpy, hf-xet, huggingface-hub, tokenizers, transformers
Successfully installed hf-xet-1.2.0 huggingface-hub-0.36.0 numpy-2.3.5 pyyaml-6.0.3 regex-2025.11.3 safetensors-0.7.0 tokenizers-0.22.1 tqdm-4.67.1 transformers-4.57.3

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [7]:
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

pretrained= "mdhugol/indonesia-bert-sentiment-classification"

model = AutoModelForSequenceClassification.from_pretrained(pretrained)
tokenizer = AutoTokenizer.from_pretrained(pretrained)

sentiment_analysis = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

/home/user/productsentiment/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

ImportError: cannot import name 'pipeline' from 'transformers' (/home/user/productsentiment/.venv/lib/python3.11/site-packages/transformers/__init__.py)

## Sample Test

In [17]:
sample_txt = input("Masukkan kalimat contoh untuk di Tes : ")
label_index = {'LABEL_0': 'positive', 'LABEL_1': 'neutral', 'LABEL_2': 'negative'}
result = sentiment_analysis(sample_txt)
status = label_index[result[0]['label']]
score = result[0]['score']
print(f'Text: {pos_text} | Label : {status} ({score * 100:.3f}%)')

print('kalimat yang dites : ', sample_txt)
print('Label              : ', status)
print(f'Score              : {score * 100:.3f}%')

Text: Sangat bahagia hari ini | Label : negative (99.117%)
kalimat yang dites :  Dia cantik kali ya, sangking cantiknya aku jadi benci
Label              :  negative
Score              : 99.117%

## Datasets Test

### Import Datasets

In [19]:
import os
from getpass import getpass

os.environ["GITHUB_USERNAME"] = input("GitHub username: ")
os.environ["GITHUB_TOKEN"] = getpass("GitHub token: ")

!git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/qee20/productsentiment.git

fatal: destination path 'productsentiment' already exists and is not an empty directory.

In [20]:
import pandas as pd
ytcomment_df = pd.read_csv("/content/productsentiment/datasets/cleanedytcomment.csv")
ytcomment_df.head()

                                       clean_comment
0                 mau nanya ini ada ia camera nya ga
1               solusi buat ngatasin iklan di hp ini
2  hp kampret ini mah nyesel beli setiap updateny...
3                 bang ada stabilizer nya buat rekam
4  tentu ada kalo mau lebih stabil pake gimbal st...

In [22]:
texts = ytcomment_df["clean_comment"].astype(str).tolist()
print("Jumlah data:", len(texts))

Jumlah data: 6128

## Inference Batching

In [23]:
from tqdm import tqdm

batch_size = 64  # GPU T4 aman (bisa 128 kalau VRAM cukup)

results = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch_texts = texts[i:i + batch_size]

    outputs = sentiment_analysis(batch_texts)

    for out in outputs:
        results.append({
            "label": label_index[out["label"]],
            "score": out["score"]
        })

100%|██████████| 96/96 [11:45<00:00,  7.35s/it]

## Put it on mytab

In [24]:
results_df = pd.DataFrame(results)

ytcomment_df["sentiment"] = results_df["label"]
ytcomment_df["confidence"] = results_df["score"]

ytcomment_df.head()

                                       clean_comment sentiment  confidence
0                 mau nanya ini ada ia camera nya ga   neutral    0.996536
1               solusi buat ngatasin iklan di hp ini   neutral    0.976811
2  hp kampret ini mah nyesel beli setiap updateny...  negative    0.998070
3                 bang ada stabilizer nya buat rekam   neutral    0.998069
4  tentu ada kalo mau lebih stabil pake gimbal st...   neutral    0.572320

## Saving result

In [30]:
!mkdir result

### Saving on Colab

In [33]:
ytcomment_df.to_csv("/content/result/labelledytcomment.csv", index=False)
print("Saved to /content/result/labelledytcomment.csv   on colab")

Saved to /content/result/labelledytcomment.csv   on colab

### Saving on relative path

In [ ]:
ytcomment_df.to_csv("../datasets/labelledytcomment.csv", index=False)
print("Saved to datasets/labelledytcomment.csv   on relative path")