In [1]:
import pandas as pd
import glob

brand = input("What to clean now?") 

paths = glob.glob(f"../data/raw/{brand}_*.csv")

dfs = [pd.read_csv(p) for p in paths]
ytcomment_df = pd.concat(dfs, ignore_index=True)

ytcomment_df = ytcomment_df[['comment']].copy()
ytcomment_df.shape

(10554, 1)

In [2]:
!pip install emoji

Requirement already satisfied: emoji in /home/user/productsentiment/.venv/lib/python3.11/site-packages (2.15.0)

In [3]:
import re
import string
import emoji

In [4]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\.\S+', ' ', text)
    text = re.sub(r'\d+', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = emoji.replace_emoji(text, replace='')
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [5]:
ytcomment_df['clean_comment'] = ytcomment_df['comment'].apply(clean_text)

ytcomment_df[['comment', 'clean_comment']].head(10)

,comment,clean_comment
0,"Btw om, saat review performance di game berat ...",btw om saat review performance di game berat i...
1,Bng mnding samsung a24 atw a52,bng mnding samsung a atw a
2,Dan saya jadi orang terakhir yg nonton video i...,dan saya jadi orang terakhir yg nonton video i...
3,Masih pakai A52 di 2023. Skip A53 dan A54 kare...,masih pakai a di skip a dan a karena pakai exynos
4,Gimana setelah 2 tahun bang?\nBanyak yang bila...,gimana setelah tahun bang banyak yang bilang l...
5,@userhplama ini baru aja dilem ulang. Kaget ju...,userhplama ini baru aja dilem ulang kaget juga...
6,@dnwinarto mantap bang,dnwinarto mantap bang
7,Sampai sekarang masih belum bisa smooth extrem...,sampai sekarang masih belum bisa smooth extrem...
8,"Body polikarbonat mate, tetep bisa jamuran ga ...",body polikarbonat mate tetep bisa jamuran ga sih
9,Bisa bang,bisa bang

In [6]:
ytcomment_df = ytcomment_df[['clean_comment']].copy()
ytcomment_df.head()

                                       clean_comment
0  btw om saat review performance di game berat i...
1                         bng mnding samsung a atw a
2  dan saya jadi orang terakhir yg nonton video i...
3  masih pakai a di skip a dan a karena pakai exynos
4  gimana setelah tahun bang banyak yang bilang l...

In [7]:
sebelum = len(ytcomment_df)
# cleaning
ytcomment_df['clean_comment'] = ytcomment_df['clean_comment'].apply(clean_text)

# hapus NaN
ytcomment_df = ytcomment_df.dropna(subset=['clean_comment'])

# hapus string kosong
ytcomment_df = ytcomment_df[ytcomment_df['clean_comment'].str.strip() != '']

# reset index
ytcomment_df = ytcomment_df.reset_index(drop=True)
sesudah = len(ytcomment_df)
print("Terbuang:", sebelum - sesudah)

Terbuang: 90

In [8]:
labels = input("What's this label for?")

ytcomment_df.to_csv(f"../data/processed/{labels}cleanedytcomment.csv", index=False)
print(f"Saved to ../data/processed/{labels}cleanedytcomment.csv")

Saved to ../data/processed/a52samsungcleanedytcomment.csv