In [1]:
%pip install pandas emoji nltk regex

Requirement already satisfied: pandas in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: emoji in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (2.15.0)
Requirement already satisfied: nltk in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (3.9.4)
Requirement already satisfied: regex in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (2026.4.4)
Requirement already satisfied: numpy>=1.26.0 in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: click in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from nltk) (1.5.3)
Requirement already satisfied: tqdm in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in /home/linuxsmol/projects/pythons/productsentiment/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import glob

brand = input("What to clean now?") 

paths = glob.glob(f"../data/raw/{brand}_*.csv")

dfs = [pd.read_csv(p) for p in paths]
ytcomment_df = pd.concat(dfs, ignore_index=True)

ytcomment_df = ytcomment_df[['comment']].copy()
ytcomment_df.shape

What to clean now? a56samsung

(7061, 1)

In [3]:
import re
import string
import emoji

In [4]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\.\S+', ' ', text)
    text = re.sub(r'\d+', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = emoji.replace_emoji(text, replace='')
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [5]:
ytcomment_df['clean_comment'] = ytcomment_df['comment'].apply(clean_text)

ytcomment_df[['comment', 'clean_comment']].head(10)

,comment,clean_comment
0,kenapa punua sayah slot sim nya d pinggir kiri...,kenapa punua sayah slot sim nya d pinggir kiri...
1,Pa Bos Samsung suruh ngeluarin Seri M lagih Ja...,pa bos samsung suruh ngeluarin seri m lagih ja...
2,"yang pake A56, layar kalian cenderung ijo/warm...",yang pake a layar kalian cenderung ijowarm ga ...
3,Dari samaung A5 2017 ke samsung A56😂,dari samaung a ke samsung a
4,Speaker outputnya yahud,speaker outputnya yahud
5,Sangat kecewa dengan Samsung dan ini bakalan t...,sangat kecewa dengan samsung dan ini bakalan t...
6,"Bang ada rekomen charger 45 watt, bisa share ..",bang ada rekomen charger watt bisa share
7,ugreen 45w,ugreen w
8,"Saya juga pake ugreen 45 watt, kalo kabel dari...",saya juga pake ugreen watt kalo kabel dari sam...
9,sinyalnya aman ga ya? karna pake exynos,sinyalnya aman ga ya karna pake exynos

In [6]:
ytcomment_df = ytcomment_df[['clean_comment']].copy()
ytcomment_df.head()

                                       clean_comment
0  kenapa punua sayah slot sim nya d pinggir kiri...
1  pa bos samsung suruh ngeluarin seri m lagih ja...
2  yang pake a layar kalian cenderung ijowarm ga ...
3                        dari samaung a ke samsung a
4                            speaker outputnya yahud

In [7]:
sebelum = len(ytcomment_df)
# cleaning
ytcomment_df['clean_comment'] = ytcomment_df['clean_comment'].apply(clean_text)

# hapus NaN
ytcomment_df = ytcomment_df.dropna(subset=['clean_comment'])

# hapus string kosong
ytcomment_df = ytcomment_df[ytcomment_df['clean_comment'].str.strip() != '']

# reset index
ytcomment_df = ytcomment_df.reset_index(drop=True)
sesudah = len(ytcomment_df)
print("Terbuang:", sebelum - sesudah)

Terbuang: 63

In [8]:
labels = input("What's this label for?")

ytcomment_df.to_csv(f"../data/processed/{labels}cleanedytcomment.csv", index=False)
print(f"Saved to ../data/processed/{labels}cleanedytcomment.csv")

What's this label for? a56samsung

Saved to ../data/processed/a56samsungcleanedytcomment.csv